CREATE TABLE agendamento( 
      contrato_id integer   , 
      id  integer generated by default as identity     NOT NULL , 
      profissional_id integer   , 
      descricao blob sub_type 1    NOT NULL , 
      horario_inicial timestamp    NOT NULL , 
      intervalo_inicial timestamp   , 
      intervalo_final timestamp   , 
      horario_final timestamp    NOT NULL , 
      cor blob sub_type 1   , 
      observacao blob sub_type 1   , 
      tipo varchar  (1)   , 
      data_agenda date   , 
      hora_inicio time   , 
      hora_fim time   , 
      hora_intervalo_inicial time   , 
      hora_intervalo_final time   , 
      hora_total time   , 
      local char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE ausencias( 
      id  integer generated by default as identity     NOT NULL , 
      profissional_id integer    NOT NULL , 
      descricao blob sub_type 1   , 
      inicio timestamp   , 
      final timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cidade( 
      id  integer generated by default as identity     NOT NULL , 
      estado_id integer    NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE colaborador( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      telefone varchar  (9)   , 
      whatsapp char  (1)   , 
      email blob sub_type 1   , 
      funcao_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE contrato( 
      id  integer generated by default as identity     NOT NULL , 
      empresa_id integer    NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
      dt_inicio date    NOT NULL , 
      dt_fim date    NOT NULL , 
      valor_hora float   , 
      cor blob sub_type 1   , 
      valor_fixo float   , 
      tipo varchar  (1)    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE contrato_item( 
      id  integer generated by default as identity     NOT NULL , 
      contrato_id integer    NOT NULL , 
      dia_semana integer   , 
      hora_inicio time   , 
      intervalo_ini time   , 
      intervalo_fim time   , 
      hora_final time   , 
      profissional_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE contrato_profissional( 
      id  integer generated by default as identity     NOT NULL , 
      contrato_id integer    NOT NULL , 
      profissional_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE empresa( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      razao blob sub_type 1   , 
      responsalvel blob sub_type 1   , 
      cidade_id integer    NOT NULL , 
      endereco blob sub_type 1   , 
      cor blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE empresa_colaborador( 
      id  integer generated by default as identity     NOT NULL , 
      empresa_id integer    NOT NULL , 
      colaborador_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE estado( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE feriado( 
      id  integer generated by default as identity     NOT NULL , 
      dt_feriado date   , 
      tipo char  (1)   , 
      descricao char  (30)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE funcao( 
      id  integer generated by default as identity     NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE profissional( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      system_user_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE realizado( 
      id  integer generated by default as identity     NOT NULL , 
      contrato_id integer    NOT NULL , 
      profissional_id integer    NOT NULL , 
      descricao blob sub_type 1    NOT NULL , 
      inicio timestamp    NOT NULL , 
      inter_inicial timestamp   , 
      inter_final timestamp   , 
      fim timestamp    NOT NULL , 
      observacao blob sub_type 1   , 
      horas float   , 
      agendamento_id integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_document( 
      id integer    NOT NULL , 
      category_id integer    NOT NULL , 
      system_user_id integer   , 
      title blob sub_type 1    NOT NULL , 
      description blob sub_type 1   , 
      submission_date date   , 
      archive_date date   , 
      filename blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_document_category( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_document_group( 
      id integer    NOT NULL , 
      document_id integer    NOT NULL , 
      system_group_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_document_user( 
      id integer    NOT NULL , 
      document_id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_group( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      uuid varchar  (36)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_group_program( 
      id integer    NOT NULL , 
      system_group_id integer    NOT NULL , 
      system_program_id integer    NOT NULL , 
      actions blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_message( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_user_to_id integer    NOT NULL , 
      subject blob sub_type 1    NOT NULL , 
      message blob sub_type 1   , 
      dt_message timestamp   , 
      checked char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_notification( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_user_to_id integer    NOT NULL , 
      subject blob sub_type 1   , 
      message blob sub_type 1   , 
      dt_message timestamp   , 
      action_url blob sub_type 1   , 
      action_label blob sub_type 1   , 
      icon blob sub_type 1   , 
      checked char  (1)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_preference( 
      id varchar  (255)    NOT NULL , 
      preference blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_program( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      controller blob sub_type 1    NOT NULL , 
      actions blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_unit( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      connection_name blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_group( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_group_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_program( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_program_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_users( 
      id integer    NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      login blob sub_type 1    NOT NULL , 
      password blob sub_type 1    NOT NULL , 
      email blob sub_type 1   , 
      frontpage_id integer   , 
      system_unit_id integer   , 
      active char  (1)   , 
      accepted_term_policy_at blob sub_type 1   , 
      accepted_term_policy char  (1)   , 
      two_factor_enabled char  (1)    DEFAULT 'N' , 
      two_factor_type varchar  (100)   , 
      two_factor_secret varchar  (255)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE system_user_unit( 
      id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

 
 CREATE UNIQUE INDEX unique_idx_profissional_system_user_id ON profissional COMPUTED BY (system_user_id);
  
 ALTER TABLE agendamento ADD CONSTRAINT fk_agendamento_1 FOREIGN KEY (contrato_id) references contrato(id); 
ALTER TABLE agendamento ADD CONSTRAINT fk_agendamento_2 FOREIGN KEY (profissional_id) references profissional(id); 
ALTER TABLE ausencias ADD CONSTRAINT fk_ausencias_1 FOREIGN KEY (profissional_id) references profissional(id); 
ALTER TABLE cidade ADD CONSTRAINT fk_cidade_1 FOREIGN KEY (estado_id) references estado(id); 
ALTER TABLE colaborador ADD CONSTRAINT fk_colaborador_2 FOREIGN KEY (funcao_id) references funcao(id); 
ALTER TABLE contrato ADD CONSTRAINT fk_contrato_1 FOREIGN KEY (empresa_id) references empresa(id); 
ALTER TABLE contrato_item ADD CONSTRAINT fk_item_contrato_1 FOREIGN KEY (contrato_id) references contrato(id); 
ALTER TABLE contrato_item ADD CONSTRAINT fk_item_contrato_2 FOREIGN KEY (profissional_id) references profissional(id); 
ALTER TABLE contrato_profissional ADD CONSTRAINT fk_contrato_profissional_1 FOREIGN KEY (contrato_id) references contrato(id); 
ALTER TABLE contrato_profissional ADD CONSTRAINT fk_contrato_profissional_2 FOREIGN KEY (profissional_id) references profissional(id); 
ALTER TABLE empresa ADD CONSTRAINT fk_empresa_1 FOREIGN KEY (cidade_id) references cidade(id); 
ALTER TABLE empresa_colaborador ADD CONSTRAINT fk_empresa_colaborador_1 FOREIGN KEY (colaborador_id) references colaborador(id); 
ALTER TABLE empresa_colaborador ADD CONSTRAINT fk_empresa_colaborador_2 FOREIGN KEY (empresa_id) references empresa(id); 
ALTER TABLE realizado ADD CONSTRAINT fk_realizado_1 FOREIGN KEY (contrato_id) references contrato(id); 
ALTER TABLE realizado ADD CONSTRAINT fk_realizado_2 FOREIGN KEY (profissional_id) references profissional(id); 
ALTER TABLE system_document ADD CONSTRAINT fk_system_document_2 FOREIGN KEY (category_id) references system_document_category(id); 
ALTER TABLE system_document ADD CONSTRAINT fk_system_document_1 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_document_group ADD CONSTRAINT fk_system_document_group_2 FOREIGN KEY (document_id) references system_document(id); 
ALTER TABLE system_document_group ADD CONSTRAINT fk_system_document_group_1 FOREIGN KEY (system_group_id) references system_group(id); 
ALTER TABLE system_document_user ADD CONSTRAINT fk_system_document_user_2 FOREIGN KEY (document_id) references system_document(id); 
ALTER TABLE system_document_user ADD CONSTRAINT fk_system_document_user_1 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_group_program ADD CONSTRAINT fk_system_group_program_1 FOREIGN KEY (system_program_id) references system_program(id); 
ALTER TABLE system_group_program ADD CONSTRAINT fk_system_group_program_2 FOREIGN KEY (system_group_id) references system_group(id); 
ALTER TABLE system_message ADD CONSTRAINT fk_system_message_1 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_message ADD CONSTRAINT fk_system_message_2 FOREIGN KEY (system_user_to_id) references system_users(id); 
ALTER TABLE system_notification ADD CONSTRAINT fk_system_notification_1 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_notification ADD CONSTRAINT fk_system_notification_2 FOREIGN KEY (system_user_to_id) references system_users(id); 
ALTER TABLE system_user_group ADD CONSTRAINT fk_system_user_group_1 FOREIGN KEY (system_group_id) references system_group(id); 
ALTER TABLE system_user_group ADD CONSTRAINT fk_system_user_group_2 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_user_program ADD CONSTRAINT fk_system_user_program_1 FOREIGN KEY (system_program_id) references system_program(id); 
ALTER TABLE system_user_program ADD CONSTRAINT fk_system_user_program_2 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_users ADD CONSTRAINT fk_system_user_1 FOREIGN KEY (system_unit_id) references system_unit(id); 
ALTER TABLE system_users ADD CONSTRAINT fk_system_user_2 FOREIGN KEY (frontpage_id) references system_program(id); 
ALTER TABLE system_user_unit ADD CONSTRAINT fk_system_user_unit_1 FOREIGN KEY (system_user_id) references system_users(id); 
ALTER TABLE system_user_unit ADD CONSTRAINT fk_system_user_unit_2 FOREIGN KEY (system_unit_id) references system_unit(id); 
